CREATE TABLE ROOM (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(100) NOT NULL, DESCRIPTION VARCHAR(100) NOT NULL, IMAGE LONGBLOB NOT NULL);
DROP TABLE IF EXISTS ROOM;
INSERT INTO ROOM (NAME, DESCRIPTION, IMAGE) VALUES ('habitacion sencilla', '1 cama, 1 tv', BYTE('/path/to/pexels-photo-338504.jpeg'));


